name: Docker Image CI

on:
  push:
    branches: [ "main", "bugfix_*" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Generate docker image name:tag
      # Should this incorporate the ${{ github.ref_name }} as well as the date?
      run: echo "img_name_tag=build_arg_parse:$(date +%s)" >> $GITHUB_ENV
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: ${{ env.img_name_tag }}
        cache-to: type=gha,mode=max
        cache-from: type=gha
        outputs: type=docker,dest=/tmp/build_arg_parse.tar
    -
      name: Load Docker image
      run: |
        docker load --input /tmp/build_arg_parse.tar
    -
      name: Build arg_parse
      run: |
        mkdir -p build_artifacts
        docker run --rm -v${PWD}:/source --user root ${{ env.img_name_tag }}
    -
      name: Run coverage tests
      run: |
        docker run --rm -v${PWD}:/source --user root ${{ env.img_name_tag }} "/source/scripts/docker/in_container/test_with_coverage.sh"
    -
      name: Test package installation
      run: |
        docker run --rm -v${PWD}:/source --user root ${{ env.img_name_tag }} "/source/scripts/docker/in_container/test_installed.sh"
    -
      name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build_artifacts